version: '3.7'

services:
  web:
    build: .
    restart: always
    depends_on:
      - prisma
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      PRISMA_ENDPOINT: http://prisma:4466

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
      - mongodb
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        schema: source/server/assets/datamodel.prisma
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
