version: '3.7'

services:
  web:
    build: .
    restart: always
    depends_on:
      - prisma
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      PRISMA_ENDPOINT: http://prisma:4466

  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    depends_on:
      - mongodb
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        schema: source/server/assets/datamodel.prisma
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongodb

  mongodb:
    image: mongo
    restart: always
    command: --smallfiles
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - 27017